using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FF16Tools.Files.Magic.Operations;

namespace FF16Tools.Files.Magic.Factories;

public class MagicOperationFactory
{
    public static IOperation Create(MagicOperationType type)
    {
        IOperation operation = type switch
        {
            MagicOperationType.Operation_1_LinearProjectile => new OpLinearProjectile(),
            MagicOperationType.Operation_25_SetupProjectileVFX => new OpSetupProjectileVFX(),
            MagicOperationType.Operation_35_SetupProjectileLifetime => new OpSetupProjectileLifetime(),
            MagicOperationType.Operation_39_OnFinishSetup => new OpOnFinishSetup(),
            MagicOperationType.Operation_40_SetupProjectileHitboxAttack => new OpSetupProjectileHitboxAttack(),
            MagicOperationType.Operation_50 => new Op50(),
            MagicOperationType.Operation_51_Initialize => new OpInitialize(),
            MagicOperationType.Operation_86 => new Op86(),
            MagicOperationType.Operation_87_SourceVFX => new OpSourceVFX(),
            MagicOperationType.Operation_92 => new Op92(),
            MagicOperationType.Operation_94_OnTargetHit => new OpOnTargetHit(),
            MagicOperationType.Operation_100 => new Op100(),
            MagicOperationType.Operation_101 => new Op101(),
            MagicOperationType.Operation_103 => new Op103(),
            MagicOperationType.Operation_108 => new Op108(),
            MagicOperationType.Operation_109 => new Op109(),
            MagicOperationType.Operation_111 => new Op111(),
            MagicOperationType.Operation_116 => new Op116(),
            MagicOperationType.Operation_121 => new Op121(),
            MagicOperationType.Operation_128 => new Op128(),
            MagicOperationType.Operation_133 => new Op133(),
            MagicOperationType.Operation_135 => new Op135(),
            MagicOperationType.Operation_137 => new Op137(),
            MagicOperationType.Operation_138 => new Op138(),
            MagicOperationType.Operation_139 => new Op139(),
            MagicOperationType.Operation_141 => new Op141(),
            MagicOperationType.Operation_144 => new Op144(),
            MagicOperationType.Operation_151 => new Op151(),
            MagicOperationType.Operation_153 => new Op153(),
            MagicOperationType.Operation_157 => new Op157(),
            MagicOperationType.Operation_169 => new Op169(),
            MagicOperationType.Operation_171 => new Op171(),
            MagicOperationType.Operation_182 => new Op182(),
            MagicOperationType.Operation_183 => new Op183(),
            MagicOperationType.Operation_186 => new Op186(),
            MagicOperationType.Operation_189 => new Op189(),
            MagicOperationType.Operation_788 => new Op788(),
            MagicOperationType.Operation_798 => new Op798(),
            MagicOperationType.Operation_990 => new Op990(),
            MagicOperationType.Operation_1470 => new Op1470(),
            MagicOperationType.Operation_CameraZoomOut => new OpCameraZoomOut(),
            MagicOperationType.Operation_1587 => new Op1587(),
            MagicOperationType.Operation_1623 => new Op1623(),
            MagicOperationType.Operation_1685 => new Op1685(),
            MagicOperationType.Operation_1825 => new Op1825(),
            MagicOperationType.Operation_1841 => new Op1841(),
            MagicOperationType.Operation_1842 => new Op1842(),
            MagicOperationType.Operation_2325 => new Op2325(),
            MagicOperationType.Operation_2366 => new Op2366(),
            MagicOperationType.Operation_2493 => new Op2493(),
            MagicOperationType.Operation_2592 => new Op2592(),
            MagicOperationType.Operation_2598 => new Op2598(),
            MagicOperationType.Operation_2855 => new Op2855(),
            MagicOperationType.Operation_3070 => new Op3070(),
            MagicOperationType.Operation_3176 => new Op3176(),
            MagicOperationType.Operation_3270 => new Op3270(),
            MagicOperationType.Operation_3294 => new Op3294(),
            MagicOperationType.Operation_3391 => new Op3391(),
            MagicOperationType.Operation_3433 => new Op3433(),
            MagicOperationType.Operation_3436 => new Op3436(),
            MagicOperationType.Operation_3515 => new Op3515(),
            MagicOperationType.Operation_3558 => new Op3558(),
            MagicOperationType.Operation_3586 => new Op3586(),
            MagicOperationType.Operation_CreateReactiveAoETrap => new OpCreateReactiveAoETrap(),
            MagicOperationType.Operation_3660 => new Op3660(),
            MagicOperationType.Operation_3771 => new Op3771(),
            MagicOperationType.Operation_3781 => new Op3781(),
            MagicOperationType.Operation_3790 => new Op3790(),
            MagicOperationType.Operation_3847 => new Op3847(),
            MagicOperationType.Operation_3877 => new Op3877(),
            MagicOperationType.Operation_3910 => new Op3910(),
            MagicOperationType.Operation_3940 => new Op3940(),
            MagicOperationType.Operation_3941 => new Op3941(),
            MagicOperationType.Operation_4015 => new Op4015(),
            MagicOperationType.Operation_4106 => new Op4106(),
            MagicOperationType.Operation_4274 => new Op4274(),
            MagicOperationType.Operation_4344 => new Op4344(),
            MagicOperationType.Operation_CameraZoomOutWithAdjust => new OpCameraZoomOutWithAdjust(),
            MagicOperationType.Operation_4448 => new Op4448(),
            MagicOperationType.Operation_4516 => new Op4516(),
            MagicOperationType.Operation_4553 => new Op4553(),
            MagicOperationType.Operation_4784 => new Op4784(),
            MagicOperationType.Operation_4828 => new Op4828(),
            MagicOperationType.Operation_4998 => new Op4998(),
            MagicOperationType.Operation_5035 => new Op5035(),
            MagicOperationType.Operation_5059 => new Op5059(),
            MagicOperationType.Operation_5068 => new Op5068(),
            MagicOperationType.Operation_5133 => new Op5133(),
            MagicOperationType.Operation_5207 => new Op5207(),
            MagicOperationType.Operation_5224 => new Op5224(),
            MagicOperationType.Operation_5231 => new Op5231(),
            MagicOperationType.Operation_5321 => new Op5321(),
            MagicOperationType.Operation_5476 => new Op5476(),
            MagicOperationType.Operation_5643 => new Op5643(),
            MagicOperationType.Operation_5722 => new Op5722(),
            MagicOperationType.Operation_5964 => new Op5964(),
            MagicOperationType.Operation_6024 => new Op6024(),
            MagicOperationType.Operation_6118 => new Op6118(),
            MagicOperationType.Operation_6264 => new Op6264(),
            MagicOperationType.Operation_6453 => new Op6453(),
            MagicOperationType.Operation_6460_CreateTrap => new OpCreateTrap(),
            MagicOperationType.Operation_6473 => new Op6473(),
            MagicOperationType.Operation_6846 => new Op6846(),
            MagicOperationType.Operation_6931 => new Op6931(),
            MagicOperationType.Operation_6942 => new Op6942(),
            MagicOperationType.Operation_7038 => new Op7038(),
            MagicOperationType.Operation_7187 => new Op7187(),
            MagicOperationType.Operation_7292 => new Op7292(),
            MagicOperationType.Operation_7378 => new Op7378(),
            MagicOperationType.Operation_7453 => new Op7453(),
            MagicOperationType.Operation_7481 => new Op7481(),
            MagicOperationType.Operation_7584 => new Op7584(),
            MagicOperationType.Operation_7732 => new Op7732(),
            MagicOperationType.Operation_7771 => new Op7771(),
            MagicOperationType.Operation_7801 => new Op7801(),
            MagicOperationType.Operation_7808 => new Op7808(),
            _ => throw new NotSupportedException($"Operation {type} is either invalid or not supported"),
        };

        return operation;
    }
}
