using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FF16Tools.Files.Magic.Operations;

public class OpInitialize : MagicOperationBase<OpInitialize>, IOperationBase<OpInitialize>
{
    public override MagicOperationType Type => MagicOperationType.Operation_51_Initialize;
    public static HashSet<MagicPropertyType> sSupportedProperties { get; set; } =
    [
        MagicPropertyType.Prop_12, 
        MagicPropertyType.Prop14_UnkMaxAngleRad, 
        MagicPropertyType.Prop_26, 
        MagicPropertyType.Prop_32, 
        MagicPropertyType.Prop_52, 
        MagicPropertyType.Prop_53, 
        MagicPropertyType.Prop_54, 
        MagicPropertyType.Prop_55, 
        MagicPropertyType.Prop_56, 
        MagicPropertyType.Prop_57, 
        MagicPropertyType.Prop_58, 
        MagicPropertyType.Prop_59, 
        MagicPropertyType.Prop_60, 
        MagicPropertyType.Prop_61, 
        MagicPropertyType.Prop_62, 
        MagicPropertyType.Prop_63, 
        MagicPropertyType.Prop_64, 
        MagicPropertyType.Prop_65, 
        MagicPropertyType.Prop_66, 
        MagicPropertyType.Prop_67,
        MagicPropertyType.Prop_68, 
        MagicPropertyType.Prop_69, 
        MagicPropertyType.Prop_70, 
        MagicPropertyType.Prop_71, 
        MagicPropertyType.Prop_72, 
        MagicPropertyType.Prop_73, 
        MagicPropertyType.Prop_74,
        MagicPropertyType.Prop_75,
        MagicPropertyType.Prop_76, 
        MagicPropertyType.Prop_77, 
        MagicPropertyType.Prop_78, 
        MagicPropertyType.Prop_79, 
        MagicPropertyType.Prop_80, 
        MagicPropertyType.Prop_81,
        MagicPropertyType.Prop_82, 
        MagicPropertyType.Prop_84, 
        MagicPropertyType.Prop_85,
        MagicPropertyType.Prop_114, 
        MagicPropertyType.Prop_185, 
        MagicPropertyType.Prop_1102, 
        MagicPropertyType.Prop_1286, 
        MagicPropertyType.Prop_1433, 
        MagicPropertyType.Prop_1434, 
        MagicPropertyType.Prop_1458, 
        MagicPropertyType.Prop_1484, 
        MagicPropertyType.Prop_1657, 
        MagicPropertyType.Prop_2396, 
        MagicPropertyType.Prop_2397, 
        MagicPropertyType.Prop_3916, 
        MagicPropertyType.Prop_3938, 
        MagicPropertyType.Prop_4010, 
        MagicPropertyType.Prop_4011, 
        MagicPropertyType.Prop_4101, 
        MagicPropertyType.Prop_4102, 
        MagicPropertyType.Prop_4103, 
        MagicPropertyType.Prop_4136, 
        MagicPropertyType.Prop_4142, 
        MagicPropertyType.Prop_4144, 
        MagicPropertyType.Prop_5119, 
        MagicPropertyType.Prop_5945, 
        MagicPropertyType.Prop_5947,
        MagicPropertyType.Prop_6383, 
        MagicPropertyType.Prop_6596, 
        MagicPropertyType.Prop_6600, 
        MagicPropertyType.Prop_6913, 
        MagicPropertyType.Prop_6975, 
        MagicPropertyType.Prop_7037, 
        MagicPropertyType.Prop_7186, 
        MagicPropertyType.Prop_7200,
        MagicPropertyType.Prop_7811
    ];
}
